{% set name = "caped-ai-metrics" %}
{% set version = "1.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/caped-ai-metrics-{{ version }}.tar.gz
  sha256: 8db6b6c16f92b6ef59d8a7926a013394cf9d044ea8285c617af53df98b5551f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - pandas
    - python >=3.9
    - scikit-image
    - scipy
    - seaborn
    - stardist

test:
  imports:
    - caped_ai_metrics
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Kapoorlabs-CAPED/caped-ai-metrics
  summary: Metric computation toolkit for segmentation and classification tasks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - kapoorlab
